### PR TITLE
dynamic authentication

### PR DESCRIPTION
**Pull request by LolHens**
This PR adds support for dynamic authentication.
My usecase for this is loading credentials/tokens from a file and authenticating the user against these.
This builds on top of #10.
image

### CODE REVIEW

**Comment by biddster** [comment]
This is interesting. Just thinking it through. 

Would it make more sense to push the credentials in via an input to the node?

**Comment by LolHens** [comment]
This way makes it possible to react to each login individually. Would the method you are suggesting also allow this kind of granular control?
My usecase is to authenticate clients using a list of tokens which are read from a file for every request.
This way I can give each client a different login token and enable/disable tokens on the fly.

Also I just wanted to clarify that the dynamic authentication functionality in this PR is only enabled if the username field is left empty so this is fully optional.

**Comment by biddster** [comment]
Understood @LolHens. Seems the only thing that is missing is documentation in the readme and index.html.

**Comment by biddster** [comment]
I suppose the other thing is that this change will break anyone using it as they will expect the existing behaviour on the first output.

**Comment by LolHens** [comment]
Maybe it would be better to make the auth output the second one.
I would do that and add some documentation.

**Comment by LolHens** [comment]
@biddster I have made the requested changes.

**Comment by biddster** [comment]
Thank you. I have 1 more question. The passive port range that's been added to the config? Should there be some UI for that?

**Comment by LolHens** [comment]
There should already be an input field in the ui for that. I've added that in #10.
In this pr I just added some validation and reformatted that code a bit to be more in line with your original code.

**Comment by biddster** [comment]
Thanks for the contribution

**Pull request merged**
